/* team-data.js — gerado pelo admin Ferraz Andrade. Não editar manualmente. */
var FALAW_TEAM = [
  { id: "t1", name: "Beatriz Domingues", role: "Advogada", email: "beatriz@falaw.com.br", status: "active", bio: "Graduada em Direito e pós-graduanda em Direito do Trabalho pela PUC-RS. Atua nas frentes trabalhista, consultiva e empresarial, com experiência em contencioso estratégico e advocacia preventiva. Especialista em Compliance Trabalhista e investigações corporativas, com foco em mitigação de riscos e prevenção de passivos." },
  { id: "t2", name: "Camilla Martinez", role: "Advogada", email: "camilla@falaw.com.br", status: "active", bio: "Graduada em Direito e pós-graduanda em Direito e Processo do Trabalho pela PUC-RS. Atua no contencioso trabalhista com experiência em acompanhamento processual, suporte à litigância e organização de rotinas jurídicas. Integra o Comitê de Inteligência Artificial do escritório." },
  { id: "t3", name: "Fernando Trevisan Jr.", role: "Advogado", email: "fernando@falaw.com.br", status: "active", bio: "Graduado em Direito e pós-graduado em Prática Trabalhista Avançada pelo Damasio Educacional. Advogado Pleno com atuação voltada à defesa de reclamadas. Experiência consolidada em contencioso, consultivo e acompanhamento processual na esfera trabalhista." },
  { id: "t4", name: "Indyara Brito", role: "Advogada", email: "indyara@falaw.com.br", status: "active", bio: "Graduada em Direito pelas Faculdades Metropolitanas Unidas (FMU) e pós-graduada em Direito Processual Civil pela Escola Paulista de Direito (EPD). Extensões em Direito Digital e Proteção de Dados pela PUC-SP e em Compliance Empresarial pela EPD. Atua com foco em conformidade regulatória, segurança da informação e riscos jurídicos no ambiente digital." },
  { id: "t5", name: "Letícia Silva", role: "Advogada Controller", email: "leticia@falaw.com.br", status: "active", bio: "Formada em Direito pela Universidade Paulista (UNIP), pós-graduada em Direito Processual do Trabalho pela Universidade Anhembi Morumbi e pós-graduanda em Legal Operations pela PUC-SP. Atua como Controller Jurídica com especialização em gestão de operações jurídicas e indicadores de performance. Formação complementar pelo Mackenzie e pela Escola Superior de Advocacia de São Paulo (ESA) com ênfase em startups. Aperfeiçoamento executivo em andamento pela FGV." },
  { id: "t6", name: "Lilian Matsumoto", role: "Advogada", email: "lilian@falaw.com.br", status: "active", bio: "Graduada em Direito pela Universidade Presbiteriana Mackenzie e pós-graduada em Direito e Processo do Trabalho pela PUC-RS. Com mais de uma década de experiência na área trabalhista, combina sólida base acadêmica ao domínio técnico das normas e ritos processuais. Atua com foco em soluções estratégicas e segurança jurídica." },
  { id: "t7", name: "Natany Valentim", role: "Advogada", email: "natany@falaw.com.br", status: "active", bio: "Graduada em Direito pela UNICASTELO e pós-graduada em Direito e Processo do Trabalho pela Universidade Legale. Atua na defesa de reclamantes e reclamadas, com experiência em audiências, sustentações orais e gestão de prazos. Condução processual estratégica com foco em defesa qualificada dos interesses dos clientes." },
  { id: "t8", name: "Pollyanna Dias", role: "Advogada", email: "pollyanna@falaw.com.br", status: "active", bio: "Formada em Direito pela Universidade Cruzeiro do Sul com láurea acadêmica. Pós-graduada em Direito Empresarial e Tributário pela UniCidade e em Direito do Trabalho e Previdenciário pelo Mackenzie. Certificada em Labor 4.0, com foco em inovação tecnológica e seus impactos no Direito do Trabalho. Fluente em inglês e francês." },
  { id: "t9", name: "Samany Cutrim", role: "Advogada", email: "samany@falaw.com.br", status: "active", bio: "Graduada em Direito pela UNICID e pós-graduada em Direito e Processo do Trabalho pelo Damasio Educacional. Graduanda em Inteligência Artificial pela FMU. Atua no contencioso e na controladoria do escritório, integrando experiência jurídica sólida a uma visão estratégica e tecnológica orientada à inovação." },
  { id: "t10", name: "Zanilda Monteiro", role: "Advogada", email: "zanilda@falaw.com.br", status: "active", bio: "Bacharela em Direito pela Universidade Paulista, pós-graduanda em Direito e Processo do Trabalho e em Legal Ops & Controladoria Jurídica. Responsável pela Controladoria Jurídica do escritório, com atuação em gestão de prazos, acompanhamento processual, padronização de fluxos internos e monitoramento de indicadores. Foco em segurança processual e eficiência operacional." },
  { id: "t11", name: "Stefhane Félix de Almeida", role: "In Memoriam", email: "", status: "memoriam", bio: "Graduada em Direito pela Universidade Paulista (2014) e especialista em Direito e Processo do Trabalho pela Escola Superior de Advocacia Paulista (2018). Advogada do Ferraz Andrade Advogados, cuja dedicação e contribuição permanecem vivas no espírito do escritório." }
];
